version: '3.9'

services:
  db:
    image: postgres
    container_name: snmpconnections
    environment:
      POSTGRES_DB: snmpdb
      POSTGRES_USER: snmp
      POSTGRES_PASSWORD: 5757
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/liv/postgres/data
volumes:
  postgres_data: